version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    container_name: todo-game-frontend
    environment:
      - REACT_APP_API_URL=https://todogame.onrender.com
    ports:
      - "3000:80"

  backend:
    build:
      context: ./backend
    container_name: todo-game-backend
    environment:
      - DATABASE_URL=postgresql://todo_game_db_600r_user:qwDOt1z4Autl91mUaBtO2crGXIVrEcgg@dpg-crdm7k5svqrc73f8850g-a.ohio-postgres.render.com:5432/todo_game_db_600r
    ports:
      - "13000:8080"
    command: sh -c "npx knex migrate:latest && npm start"

volumes:
  todo-game-db-data: